plugins {
    id 'com.android.library'
    id "com.vanniktech.maven.publish"
}

android {
    namespace 'cn.bingerz.flipblelib'
    compileSdkVersion build_versions.target_sdk
    buildToolsVersion build_versions.build_tools

    defaultConfig {
        minSdkVersion build_versions.min_sdk
        targetSdkVersion build_versions.target_sdk

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "androidx.appcompat:appcompat:$versions.appcompat"

    // Dependencies for local unit tests
    testImplementation "junit:junit:$versions.junit"
    testImplementation "org.mockito:mockito-core:$versions.mockito"
    testImplementation "org.hamcrest:hamcrest-all:$versions.hamcrest"
    testImplementation "org.powermock:powermock-module-junit4:$versions.powerMockito"
    testImplementation "org.powermock:powermock-api-mockito:$versions.powerMockito"

    // Android Testing Support Library's runner and rules
    androidTestImplementation "com.android.support.test:runner:$versions.runner"
    androidTestImplementation "com.android.support.test:rules:$versions.rules"

    // Espresso UI Testing dependencies.
    androidTestImplementation "com.android.support.test.espresso:espresso-core:$versions.espresso"
    androidTestImplementation "com.android.support.test.espresso:espresso-contrib:$versions.espresso"
    androidTestImplementation "com.android.support.test.espresso:espresso-intents:$versions.espresso"

}

//Gradle Maven Publish Plugin Script Configuration
//Run Script: ./gradlew publish

def versionName = "0.8.4"
def groupName = "cn.bingerz.android"
def artifactName = "flipble"
def siteUrl = 'https://github.com/bingerz/flip-ble'
def gitUrl = 'https://github.com/bingerz/flip-ble.git'
def repositorySnapshotUrl = "https://oss.sonatype.org/content/repositories/snapshots/"
def repositoryReleaseUrl = "https://oss.sonatype.org/service/local/staging/deploy/maven2/"

task generateSourcesJar(type: Jar) {
    from android.sourceSets.main.java.srcDirs
    archiveClassifier.set('sources')
}

mavenPublishing {
    coordinates(groupName, artifactName, versionName)

    pom {
        name = "FlipBLE"
        description = "A stable, easy-to-use framework developed based on the Android Bluetooth Low Energy API."
        inceptionYear = "2021"
        url = siteUrl
        licenses {
            license {
                name = 'The Apache Software License, Version 2.0'
                url = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
                distribution = "http://www.apache.org/licenses/LICENSE-2.0.txt"
            }
        }
        developers {
            developer {
                id = findProperty("developer.id")
                name = findProperty("developer.name")
                email = findProperty("developer.email")
                url = "https://github.com/bingerz"
            }
        }
        scm {
            url = siteUrl
            connection = gitUrl
            developerConnection = gitUrl
        }
    }
}